In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [4]:
df=pd.read_csv('emails.csv')

In [5]:
df

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5728 rows x 2 columns]

In [6]:
df['spam'].value_counts()

0    4360
1    1368
Name: spam, dtype: int64

In [7]:
df.drop_duplicates(inplace=True)

In [8]:
df['spam'].value_counts()

0    4327
1    1368
Name: spam, dtype: int64

In [9]:
df

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5695 rows x 2 columns]

In [10]:
df.isnull().sum()

text    0
spam    0
dtype: int64

### Saparate x and y

In [11]:
x=df.text.values

In [12]:
y=df.spam.values

DataSet Split

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

### Data  Preprocessing

In [19]:
from sklearn.feature_extraction.text import CountVectorizer

In [20]:
cv=CountVectorizer()

In [21]:
res=cv.fit_transform(x_train)

In [22]:
res.toarray()

array([[0, 0, 6, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 2, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [23]:
res.shape

(4556, 33662)

### ML Naive_base Algorithm

In [24]:
from sklearn.naive_bayes import MultinomialNB

In [25]:
model=MultinomialNB()

In [26]:
model.fit(res,y_train)

MultinomialNB()

In [27]:
xtest=cv.transform(x_test)

In [30]:
xtest.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [31]:
model.score(xtest,y_test)

0.9894644424934153

In [32]:
 emails = ['hey i am lokking for machine learning tutorial in begali language','hey you win an iphone x giveaway for free please do the survey']

In [33]:
cv_emails=cv.transform(emails)

In [35]:
cv_emails.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [36]:
model.predict(cv_emails)

array([0, 1], dtype=int64)

### Performance

In [37]:
pred=model.predict(xtest)

In [38]:
pred

array([0, 1, 0, ..., 0, 0, 1], dtype=int64)

In [39]:
from sklearn.metrics import accuracy_score

In [40]:
accuracy_score(pred,y_test)

0.9894644424934153

### Confusion matrix

In [41]:
from sklearn.metrics import confusion_matrix

In [42]:
confusion_matrix(y_test,pred)

array([[859,   7],
       [  5, 268]], dtype=int64)

### TP=859,FP=7,FN=5,TN=268

### CLASSIFICATION

In [43]:
from sklearn.metrics import classification_report

In [44]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       866
           1       0.97      0.98      0.98       273

    accuracy                           0.99      1139
   macro avg       0.98      0.99      0.99      1139
weighted avg       0.99      0.99      0.99      1139

