Python is an interpreted, high-level, and general-purpose programming language. Created by Guido van Rossum and first released in 1991. Python has a simple syntax similar to the English language. Python has a syntax that allows developers to write programs with fewer lines than some other programming languages. Python runs on an interpreter system, meaning that code can be executed as soon as it is written.

# Introduction to Python Variables || Variable Explained

Q: পাইথন প্রোগ্রামিং (Python Programming) দিয়ে কি কাজ করা যায় ?? Ans: পাইথন (Python) একটি বস্তু-সংশ্লিষ্ট (Object Oriented) উচ্চস্তরের (High Level) প্রোগ্রামিং ভাষা (Programming Language)। ১৯৯১ সালে গুইডো ভ্যান রস্যিউম এটি প্রথম প্রকাশ করেন। পাইথন নির্মাণ করার সময় প্রোগ্রামের পঠনযোগ্যতার উপর বেশি গুরুত্ব দেয়া হয়েছে। এখানে প্রোগ্রামারের পরিশ্রমকে কম্পিউটারের চেয়ে বেশি গুরুত্ব দেয়া হয়েছে। ভবিষ্যৎ প্রযুক্তির ভিত্তি ডাটা সায়েন্স (Data Science) ও মেশিন লার্নিং (Machine Learning), সর্বোপরি আর্টিফিশিয়াল ইন্টেলিজেন্স (AI) নিয়ে কাজ করতে চাইলে পাইথন প্রোগ্রামিং হতে পারে নির্দ্বিধায় আপনার প্রথম পছন্দ। কারণ- scikit-learn এর মতো মেশিন লার্নিং (Machine Learning) লাইব্রেরী, Pandas এর মতো ডাটা ফ্রেম লাইব্রেরী এবং Numpy এর মতো ক্যালকুলেশন লাইব্রেরী এসবই আছে পাইথনের (Python) জন্য। আরো নির্দিষ্ট করে বলতে গেলে পাইথন (Python) এর উপর ভিত্তি করে- Django, Tornado, Flask ইত্যাদি ফ্রেমওয়ার্ক এর মাধ্যমে আপনি খুব সহজেই ওয়েব অ্যাপ্লিকেশন ডেভেলপমেন্ট করতে পারবেন। আর গেমস ডেভেলপমেন্ট করতে চাইলে আপনার জন্য রয়েছে PyGame. আপনি যদি Internet of Things (IoT) নিয়ে কাজ করতে চান, তাহলে আপনার জন্য রয়েছে RPi.GPIO বা Raspberrypi এর মত হার্ডওয়্যার প্ল্যাটফর্ম। আবার গ্রাফিক্যাল ইউজার ইন্টারফেইস (GUI) সমৃদ্ধ সফটওয়্যার ডেভেলপমেন্টের জন্য এই ল্যাঙ্গুয়েজ এর উপর ভিত্তি করে আপনার জন্য রয়েছে Tkinter এর মত প্যাকেজ বা PyQT এর মত টুলকিট। আরো রয়েছে Kivy এর মতো লাইব্রেরী। Tk, PyQt, PyGTK ইত্যাদি দিয়ে ডেস্কটপ অ্যাপ ডেভেলপমেন্ট বেশ ভালোই চলছে। Kivy দিয়ে কিছু কাজ হলেও মোবাইল অ্যাপের বিশাল বাজারে পাইথনের (Python) দখল প্রায় নেই বললেই চলে। এটি পাইথনের (Python) একটি বড় সীমাবদ্ধতা। বর্তমানে পাইথনের সবচেয়ে বড় বাজার হচ্ছে ওয়েব প্রোগ্রামিং (Web Programming)। তুলনামূলকভাবে অনেক সহজ হওয়ায় শিশুদের প্রোগ্রামিংয়ের সাথে পরিচয় করাতে বেশিরভাগ ক্ষেত্রেই পাইথন (Python) ব্যবহার করা হয়। দৈনন্দিন বিভিন্ন বিরক্তিকর কাজ, যেগুলো বারবার করতে হয়, সেগুলো অটোমেট করতে পাইথন (Python) ব্যবহার করা হচ্ছে।

In [1]:
print(2)

2


In [2]:
print('Hamid Hosen')

Hamid Hosen


In [3]:
x=2
y='Hamid Hosen'

print(x)
print(y)

2
Hamid Hosen


In [4]:
x=2
y='Hamid Hosen'
x=5

print(x)
print(y)

5
Hamid Hosen


In [5]:
x,y,z=1,2,3
print(x)
print(x,y)
print(x,y,z)

1
1 2
1 2 3


# Memory Management for Python Variables ||Study Mart

In [6]:
x=100
print(x)

100


In [7]:
print(id(x))

140726335320960


In [8]:
y=x;
print(id(y))
print(id(x))
print(id(100))

140726335320960
140726335320960
140726335320960


In [9]:
x=10
y=90
z=10+90

print(id(x))
print(id(y))
print(id(z))

140726335318080
140726335320640
140726335320960


In [10]:
print(id('Hamid'))

2295746918576


# Escape Sequence & Comments in Python

In [11]:
x='Hamid Hosen'
y="EDU"
z=191002012

print(x)

Hamid Hosen


In [12]:
x='Hamid Hosen'
y="EDU"
z=191002012
#r=3903

print(r)

NameError: name 'r' is not defined

# Multiline comment

In [13]:
'''
x=Md.Hamid Hosen
East Delta University
CSE

print(x)

'''

'\nx=Md.Hamid Hosen\nEast Delta University\nCSE\n\nprint(x)\n\n'

# Escape Sequence

In [14]:
print("Hamid \nHosen")

Hamid 
Hosen


In [15]:
print('Hamid\'s Hosen')

Hamid's Hosen


In [16]:
print('Hamid\'s "Hosen"')

Hamid's "Hosen"


In [17]:
print('Hamid\'s \\n Hosen')

Hamid's \n Hosen


# Data Types in Python 

In [18]:
x=10
type(x)

int

In [19]:
x=5.5
print(type(x))

<class 'float'>


In [20]:
x=4+4j
print(type(x))

<class 'complex'>


In [21]:
x=5
y=8

print(type(x==y))

<class 'bool'>


In [22]:
x='Hamid Hosen'
print(type(x))

<class 'str'>


In [23]:
x=[1,2,3,4,5]
print(type(x))

<class 'list'>


In [24]:
x=(1,2,3,4,5)
print(type(x))

<class 'tuple'>


In [25]:
x={1,2,3,4,5}
print(type(x))

<class 'set'>


# User input in Python

In [26]:
x=10
y=3
z=x*y

print(z)

30


In [27]:
x=input()

34


In [28]:
x=input('Enter any number:')

Enter any number:34


In [29]:
x=input('Enter any number:')
y=input('Enter any number:')

z=x+y

print(z)

Enter any number:4
Enter any number:5
45


In [30]:
print(type(z))

<class 'str'>


In [31]:
a=int(input("Enter any number:"))
b=int(input('Enter any number:'))

z=a+b

print(z)

Enter any number:3
Enter any number:4
7


In [32]:
a=float(input("Enter any number:"))
b=float(input('Enter any number:'))

z=a+b

print(z)

Enter any number:3.5
Enter any number:3.5
7.0


# Operators in Python

# Arithmetic Operator

In [33]:
a=10
b=3

print(a+b)

13


In [34]:
print(a-b)

7


In [35]:
print(a*b)

30


In [36]:
print(a/b)

3.3333333333333335


In [37]:
print(a%b)

1


In [38]:
print(a**b)

1000


In [39]:
print(a//b)

3


# Assignment Operator

In [41]:
a=10
b=3
c=a+b#Assignment Operator
print(c)

13


In [42]:
a=10
b=3
c=a+b#Assignment Operator
c+=a#c=c+a
print(c)

23


# Relational Operator

In [43]:
x=5
y=3

print(a<b)

False


In [44]:
print(a<=b)

False


In [45]:
print(a>b)

True


In [46]:
print(a>=b)

True


In [47]:
print(a==b)

False


In [48]:
print(a!=b)

True


# Logical Operator

In [49]:
a=5
b=3

c=a>b or a<b

print(c)

True


In [50]:
a=5
b=3

c=a>b and a<b

print(c)

False


# Unary Operator

In [51]:
a=10
b=1
c=5
c=-c

print(c)

-5


In [52]:
a=10
b=1
c=5
c=-c
c=-c

print(c)

5


# Strings in Python

In [53]:
a="Hamid Hosen"
print(a)

Hamid Hosen


In [54]:
print(a[0])

H


In [55]:
print(a[2:5])

mid


In [56]:
print(a[-7:-3])

d Ho


In [57]:
print(len(a))

11


In [58]:
a="  Hamid Hosen"
print(a)

  Hamid Hosen


In [59]:
print(a.strip())

Hamid Hosen


In [60]:
a="Hamid Hosen"
print(a.upper())

HAMID HOSEN


In [61]:
a="Hamid Hosen"
print(a.lower())

hamid hosen


In [62]:
name="Hamid Hosen Azad"
print(name.split())

['Hamid', 'Hosen', 'Azad']


In [64]:
a="Hamid Azad"
print(a.replace("Azad","Hosen"))

Hamid Hosen


# Arrays in Python

In [65]:
from array import *
salary=array('i',[100,200,300,400])
print(salary)

array('i', [100, 200, 300, 400])


In [66]:
print(salary[0])

100


In [67]:
for i in salary:
    print(i)

100
200
300
400


In [68]:
for i in range(4):
    print(salary[i])

100
200
300
400


In [69]:
print(salary.buffer_info())

(2295744472144, 4)


In [70]:
print(salary.append(500))

None


In [71]:
print(salary)

array('i', [100, 200, 300, 400, 500])


In [72]:
print(salary.remove(300))

None


In [73]:
print(salary)

array('i', [100, 200, 400, 500])


In [74]:
salary.reverse()
print(salary)

array('i', [500, 400, 200, 100])


In [75]:
salary=array('i',[100,200.5,300,400])
print(salary) # int and float are same time not use

TypeError: integer argument expected, got float

In [76]:
salary=array('f',[100,200.5,300,400])
print(salary) 

array('f', [100.0, 200.5, 300.0, 400.0])


# Python Bangla Tutorial for Beginners

# List

In [77]:
list=[1,4,2,3.5,7,6,4]
print(list)

[1, 4, 2, 3.5, 7, 6, 4]


In [78]:
list=[1,25,4,['Hamid',34,5],40,60]
print(list)

[1, 25, 4, ['Hamid', 34, 5], 40, 60]


In [79]:
print(list[3])

['Hamid', 34, 5]


In [80]:
print(list[3][0])

Hamid


In [81]:
list=list+[1,2,3,4]
print(list)

[1, 25, 4, ['Hamid', 34, 5], 40, 60, 1, 2, 3, 4]


In [82]:
list.extend([6,7,8,9,10])
print(list)

[1, 25, 4, ['Hamid', 34, 5], 40, 60, 1, 2, 3, 4, 6, 7, 8, 9, 10]


In [83]:
list.remove(1)
print(list)

[25, 4, ['Hamid', 34, 5], 40, 60, 1, 2, 3, 4, 6, 7, 8, 9, 10]


In [84]:
list.remove(list[2])
print(list)

[25, 4, 40, 60, 1, 2, 3, 4, 6, 7, 8, 9, 10]


In [85]:
list=[1,1,1,2,3,4,5]
print(list.count(1))

3


# Tuple in Python

In [86]:
tuple=(1,24,56,7,89)
print(tuple)

(1, 24, 56, 7, 89)


In [87]:
import sys

tuple=(1,2,3,4,5)
list=[1,2,3,4,5]

print('tuple',sys.getsizeof(tuple))
print('list',sys.getsizeof(list))

tuple 80
list 96


In [88]:
del tuple
print(tuple)

<class 'tuple'>


# Sets in Python

In [89]:
s1=set([1,2,3,4,5])
print(s1)

{1, 2, 3, 4, 5}


In [90]:
print(type(s1))

<class 'set'>


In [91]:
s1={1,2,3,3,4,5}
print(s1)

{1, 2, 3, 4, 5}


In [92]:
s1.add(6)
print(s1)

{1, 2, 3, 4, 5, 6}


In [93]:
s1.update((7,8,9,10))
print(s1)

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}


In [94]:
s1.update([11,12,13,14,15])
print(s1)

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15}


In [95]:
s1={1,2,3,4,5}
s2={6,7,8,9,10}
s1.update(s2)
print(s1)

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}


In [97]:
s1.remove(1)
print(s1)

{2, 3, 4, 5, 6, 7, 8, 9, 10}


In [98]:
s1.discard(15)
print(s1)

{2, 3, 4, 5, 6, 7, 8, 9, 10}


In [99]:
s1.discard(10)
print(s1)

{2, 3, 4, 5, 6, 7, 8, 9}


# Sets in Python || Intersection Operation in Python

In [100]:
s1={1,2,3}
s2={2,3,4}
s3={3,4,5}

s4=s1.intersection(s2)
print(s4)

{2, 3}


In [101]:
s5=s1.intersection(s2,s3)
print(s5)

{3}


In [102]:
print(s1.difference(s2))

{1}


In [103]:
print(s2.difference(s1))

{4}


In [104]:
print(s1.symmetric_difference(s2))

{1, 4}


In [105]:
print(s2.symmetric_difference(s1))

{1, 4}


In [106]:
s1=[1,1,2,2,3,3,3,3,4,5]
r=set(s1)
print(r)

{1, 2, 3, 4, 5}


In [107]:
s1=[1,2,3]
s2=[2,3,4]

print(set(s1).difference(set(s2)))

{1}


# Sets in Python || Union Operation in Python

In [108]:
a={1,2,3,4,5}
b={2,3,6,8,9}
c={5,6,9,1,10}

r=a.union(b)
print(r)

{1, 2, 3, 4, 5, 6, 8, 9}


In [109]:
r=a.union(b,c)
print(r)

{1, 2, 3, 4, 5, 6, 8, 9, 10}


In [110]:
r=a|b
print(r)

{1, 2, 3, 4, 5, 6, 8, 9}


In [111]:
r=a|b|c
print(r)

{1, 2, 3, 4, 5, 6, 8, 9, 10}


# Python Dictionaries || Dictionary in Python

In [112]:
d={'name':"Hamid Hosen",'age':22,'Bdate':1999}
print(d)

{'name': 'Hamid Hosen', 'age': 22, 'Bdate': 1999}


In [113]:
print(d['name'])

Hamid Hosen


In [114]:
d1={'name':"Hamid Hosen",10:10,10.5:10.5,True:True,(2,3):5}
print(d1)

{'name': 'Hamid Hosen', 10: 10, 10.5: 10.5, True: True, (2, 3): 5}


In [115]:
print(d1[(2,3)])

5


In [116]:
d2=d1;
print(d2)

{'name': 'Hamid Hosen', 10: 10, 10.5: 10.5, True: True, (2, 3): 5}


In [117]:
d2=d1.copy()
print(d2)

{'name': 'Hamid Hosen', 10: 10, 10.5: 10.5, True: True, (2, 3): 5}


In [118]:
x=len(d1)
print(x)

5


In [119]:
y=len(d)
print(y)

3


In [120]:
d1['versity']='Daffodil University'
print(d1)

{'name': 'Hamid Hosen', 10: 10, 10.5: 10.5, True: True, (2, 3): 5, 'versity': 'Daffodil University'}


In [121]:
d1.pop('versity')
print(d1)

{'name': 'Hamid Hosen', 10: 10, 10.5: 10.5, True: True, (2, 3): 5}


In [122]:
d1.clear()
print(d1)

{}


# Python Dictionaries || Dictionary in Python

In [123]:
d={1:'study Mart',2:'Data Science',3:'Python'}
print(d[1])

study Mart


In [124]:
print(d.get(2))

Data Science


In [125]:
print(d.items())

dict_items([(1, 'study Mart'), (2, 'Data Science'), (3, 'Python')])


In [126]:
d={1:'study Mart','Data Science':2,3:'Python'}
print(d.keys())

dict_keys([1, 'Data Science', 3])


In [127]:
print(d.values())

dict_values(['study Mart', 2, 'Python'])


# Python Nested Dictionary

In [128]:
student={1:{'name':'Hamid','age':21,'sex':'male'},
        2:{'name':'Hamid Hosen','age':22,'sex':'male'},
        3:{'name':'Hamid Hosen Azad','age':24,'sex':'male'}
        }
print(student)

{1: {'name': 'Hamid', 'age': 21, 'sex': 'male'}, 2: {'name': 'Hamid Hosen', 'age': 22, 'sex': 'male'}, 3: {'name': 'Hamid Hosen Azad', 'age': 24, 'sex': 'male'}}


In [129]:
print(student[1])

{'name': 'Hamid', 'age': 21, 'sex': 'male'}


In [130]:
print(student[1]['sex'])
print(student[2]['name'])
print(student[3]['age'])

male
Hamid Hosen
24


In [131]:
student={1:{'name':'Hamid','age':21,'sex':'male'},
        2:{'name':'Hamid Hosen','age':22,'sex':'male'},
        3:{'name':'Hamid Hosen Azad','age':24,'sex':'male'}
        }

print(student[1]['sex'])
print(student[2]['name'])
print(student[3]['age'])

student[4]={}
student[4]['name']='Md.Hamid Hosen'
student[4]['age']=24
student[4]['sex']='male'

print(student[3])

male
Hamid Hosen
24
{'name': 'Hamid Hosen Azad', 'age': 24, 'sex': 'male'}


In [132]:
print(student)

{1: {'name': 'Hamid', 'age': 21, 'sex': 'male'}, 2: {'name': 'Hamid Hosen', 'age': 22, 'sex': 'male'}, 3: {'name': 'Hamid Hosen Azad', 'age': 24, 'sex': 'male'}, 4: {'name': 'Md.Hamid Hosen', 'age': 24, 'sex': 'male'}}


In [133]:
student.pop(1)
print(student)

{2: {'name': 'Hamid Hosen', 'age': 22, 'sex': 'male'}, 3: {'name': 'Hamid Hosen Azad', 'age': 24, 'sex': 'male'}, 4: {'name': 'Md.Hamid Hosen', 'age': 24, 'sex': 'male'}}


In [134]:
del student[4]['sex']
print(student)

{2: {'name': 'Hamid Hosen', 'age': 22, 'sex': 'male'}, 3: {'name': 'Hamid Hosen Azad', 'age': 24, 'sex': 'male'}, 4: {'name': 'Md.Hamid Hosen', 'age': 24}}


In [135]:
student[2].pop('sex')
print(student)

{2: {'name': 'Hamid Hosen', 'age': 22}, 3: {'name': 'Hamid Hosen Azad', 'age': 24, 'sex': 'male'}, 4: {'name': 'Md.Hamid Hosen', 'age': 24}}


In [136]:
del student[4]
print(student)

{2: {'name': 'Hamid Hosen', 'age': 22}, 3: {'name': 'Hamid Hosen Azad', 'age': 24, 'sex': 'male'}}


# If, elif and else Statements in Python 

In [137]:
x=int(input())
y=int(input())
z=int(input())

if(x<y):
    print('x is less then y' )

10
20
30
x is less then y


In [138]:
x=int(input())
y=int(input())
z=int(input())

if(x>y):
    print('x is less then y' )

20
10
10
x is less then y


# Find Odd & Even Number in Python

In [139]:
num=int(input("Enter any number:"))

if num%2==0:
    print("Ever number.")
else:
    print("Odd number.")

Enter any number:5
Odd number.


# Find Negative & Positive Number in Python

In [140]:
num=int(input("Enter any number:"))

if num==0:
    print('The number is zero.')
elif num>0:
    print('The number is positive.')
else:
    print('The number is Negative.')

Enter any number:5
The number is positive.


# Nested if statement in Python

In [141]:
num=int(input("Enter any number:"))

if num==0:
    print('The number is zero.')
elif num>0:
    print('The number is positive.')
    
    if(num%2==0):
        print("The number is even.")
    else:
        print("The number is odd.")
else:
    print('The number is Negative.')

Enter any number:100
The number is positive.
The number is even.


# Find Max Number out of three Numbers using Python

In [142]:
num1=int(input("Enter the first number:"))
num2=int(input("Enter the second number:"))
num3=int(input("Enter the second number:"))

if num1>num2:
    if num1>num3:
        print('Number1 is bigger then number2,number3')
    else:
        print('Number3 is bigger then number1,number2')
elif num1<num2:
    if num2>num3:
        print('Number2 is bigger then number1,number3')
    else:
         print('Number3 is bigger then number1,number2')

Enter the first number:10
Enter the second number:30
Enter the second number:20
Number2 is bigger then number1,number3


In [143]:
num1=int(input("Enter the first number:"))
num2=int(input("Enter the second number:"))
num3=int(input("Enter the second number:"))

if num1>num2:
    if num1>num3:
        print('Number1 is bigger then number2,number3')
    else:
        print('Number3 is bigger then number1,number2')
elif num1<num2:
    if num2>num3:
        print('Number2 is bigger then number1,number3')
    else:
         print('Number3 is bigger then number1,number2')

Enter the first number:20
Enter the second number:30
Enter the second number:50
Number3 is bigger then number1,number2


# Ternary Operator in Python

In [144]:
#r=A if condition else B

print('yes!' if True else 'No!')

yes!


In [145]:
print('yes!' if False else 'No!')

No!


In [146]:
a,b=10,20
print(a if a<b else b)

10


In [147]:
num=int(input("Enter any number:"))

print('The number is even.' if num%2==0 else "The number is odd.")

Enter any number:5
The number is odd.


# Swap two Numbers in Python

In [148]:
a=5
b=10

c=a
a=b
b=c

print(a,b)

10 5


In [149]:
a=10
b=5

a=a+b
b=a-b
a=a-b

print(a,b)

5 10


In [150]:
a=10
b=20

a,b=b,a
print(a,b)

20 10


# Exceptions Handling in Python

In [151]:
a=5
b=2

print(a/b)

2.5


In [152]:
a=5
b=0

print(a/b)
print('ok,Bey')

ZeroDivisionError: division by zero

In [153]:
a=5
b=0

try:
    print(a/b)
except Exception:
    print('You can not divide a number by zero!')
print('ok,Bey')

You can not divide a number by zero!
ok,Bey


In [155]:
a=5
b=2

try:
    print(a/b)
except Exception:
    print('You can not divide a number by zero!')
print('ok,Bey')

2.5
ok,Bey


In [157]:
a=5
b=0

try:
    print(a/b)
except Exception as e:
    print('You can not divide a number by zero!',e)
print('ok,Bey')

You can not divide a number by zero! division by zero
ok,Bey


In [158]:
a=5
b=0

try:
    print("Resourse open.")
    print(a/b)
    print("Resourse close.")
except Exception as e:
    print('You can not divide a number by zero!',e)
print('ok,Bey')

Resourse open.
You can not divide a number by zero! division by zero
ok,Bey


In [159]:
a=5
b=2

try:
    print("Resourse open.")
    print(a/b)
    print("Resourse close.")
except Exception as e:
    print('You can not divide a number by zero!',e)
print('ok,Bey')

Resourse open.
2.5
Resourse close.
ok,Bey


In [160]:
a=5
b=0

try:
    print("Resourse open.")
    print(a/b)
    
except Exception as e:
    print('You can not divide a number by zero!',e)

finally:
    print("Resourse close.")
    
print('ok,Bey')

Resourse open.
You can not divide a number by zero! division by zero
Resourse close.
ok,Bey


In [161]:
a=5
b=2

try:
    print("Resourse open.")
    print(a/b)
    
except Exception as e:
    print('You can not divide a number by zero!',e)

finally:
    print("Resourse close.")
    
print('ok,Bey')

Resourse open.
2.5
Resourse close.
ok,Bey


In [162]:
a=5
b=2

try:
    print("Resourse open.")
    print(a/b)
    
    n=int(input("Enter any number:"))
    
except Exception as e:
    print('You can not divide a number by zero!',e)

finally:
    print("Resourse close.")
    
print('ok,Bey')

Resourse open.
2.5
Enter any number:2.5
You can not divide a number by zero! invalid literal for int() with base 10: '2.5'
Resourse close.
ok,Bey


In [163]:
a=5
b=2

try:
    print("Resourse open.")
    print(a/b)
    
    n=int(input("Enter any number:"))
    
except Exception as e:
    print('You can not divide a number by zero!',e)

finally:
    print("Resourse close.")
    
print('ok,Bey')

Resourse open.
2.5
Enter any number:xyz
You can not divide a number by zero! invalid literal for int() with base 10: 'xyz'
Resourse close.
ok,Bey


In [164]:
a = 5
b = 2

try:
    print("Resourse open.")
    print(a / b)

    n = int(input("Enter any number:"))

except ZeroDivisionError:
    print('You can not divide a number by zero!')

except ValueError:
    print("Sometimes")

finally:
    print("Resourse close.")

print('ok,Bey')

Resourse open.
2.5
Enter any number:xyz
Sometimes
Resourse close.
ok,Bey


In [165]:
a = 5
b = 0

try:
    print("Resourse open.")
    print(a / b)

    n = int(input("Enter any number:"))

except ZeroDivisionError:
    print('You can not divide a number by zero!')

except ValueError:
    print("Sometimes")

finally:
    print("Resourse close.")

print('ok,Bey')

Resourse open.
You can not divide a number by zero!
Resourse close.
ok,Bey


In [166]:
a = 5
b = 2

try:
    print("Resourse open.")
    print(a / b)

    n = int(input("Enter any number:"))

except (ZeroDivisionError,ValueError):
    print('You can not divide a number by zero!')
    print("Sometimes")

finally:
    print("Resourse close.")

print('ok,Bey')

Resourse open.
2.5
Enter any number:xyz
You can not divide a number by zero!
Sometimes
Resourse close.
ok,Bey


# Assertions in Python | Python Assert Statement | Python Assert Keyword

In [167]:
def salary(n):
    print("My salary is ",n)
salary(500)

My salary is  500


In [168]:
def salary(n):
    #assert  <condition>,'message'
    assert n>0, 'Salary cannot less then zero'
    print("My salary is ",n)
salary(-500)

AssertionError: Salary cannot less then zero

In [169]:
def salary(n):
    #assert  <condition>,'message'
    assert n>0, 'Salary cannot less then zero'
    print("My salary is ",n)
salary(500)

My salary is  500


# How to Use Mathematical Functions in Python

In [170]:
x=25.5
print(x**4)

422825.0625


In [171]:
import math
print(math.pow(x,4))

422825.0625


In [172]:
print(math.sqrt(x))

5.049752469181039


In [173]:
print(math.pi)

3.141592653589793


In [174]:
print(math.e)

2.718281828459045


In [175]:
x=25
print(math.factorial(x))

15511210043330985984000000


In [176]:
print(math.remainder(x,2))

1.0


In [177]:
print(math.tau)

6.283185307179586


In [178]:
print(math.inf)

inf


In [179]:
print(math.nan)

nan


In [180]:
x=25.5
print(math.ceil(x))

26


In [181]:
print(math.floor(x))

25


In [182]:
import math as m

x=25.6

print(m.degrees(x))

1466.7719555349076


In [183]:
print(math.degrees(x))#radious to degree

1466.7719555349076


In [184]:
print(math.radians(x))#degree to radians

0.4468042885105484


In [185]:
#heyperbolic function
print(m.asinh(x))

3.9361207836781484


In [186]:
print(m.acosh(x))

3.9353578438549484


In [187]:
print(m.asinh(x))

3.9361207836781484


In [188]:
print(m.sin(x))

0.4504405942753893


In [189]:
print(m.cos(x))

0.8928064017629097


In [190]:
help(math)

Help on built-in module math:

NAME
    math

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.
    
    acosh(x, /)
        Return the inverse hyperbolic cosine of x.
    
    asin(x, /)
        Return the arc sine (measured in radians) of x.
    
    asinh(x, /)
        Return the inverse hyperbolic sine of x.
    
    atan(x, /)
        Return the arc tangent (measured in radians) of x.
    
    atan2(y, x, /)
        Return the arc tangent (measured in radians) of y/x.
        
        Unlike atan(y/x), the signs of both x and y are considered.
    
    atanh(x, /)
        Return the inverse hyperbolic tangent of x.
    
    ceil(x, /)
        Return the ceiling of x as an Integral.
        
        This is the smallest integer >= x.
    
    comb(n, k, /)
        Number of ways to choose k items from n items without repetition and without order

# Introduction to For Loop & Range Function in Python

In [191]:
a=['CSE','EEE','ME','ChE','Civil']
print(a[0])
print(a[1])
print(a[2])
print(a[3])
print(a[4])

CSE
EEE
ME
ChE
Civil


In [192]:
for i in a:
    print(i)

CSE
EEE
ME
ChE
Civil


In [193]:
b=[10,20,30,40,50]
total=0

for i in b:
    total+=i
print(total)

150


In [194]:
c=list(range(1,11))
print(c)

TypeError: 'list' object is not callable

In [195]:
c=set(range(1,11))
print(c)

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}


In [196]:
c=tuple(range(1,11))
print(c)

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)


In [197]:
total=0

for i in range(1,11):
    total+=i
print(total)

55


In [198]:
total=0

for i in range(1,11):
    if(i%2)==0:
        total+=i
print(total)

30


# Find Prime Numbers in Python

In [199]:
num=int(input("Enter any number:"))

for i in range(2,num):
    if num%i==0:
        print('Not a prime number.')
        break;
else:
    print('Oh! its a prime number.')

Enter any number:4
Not a prime number.


# Break Statement in Python

In [200]:
n=int(input("Enter any number:"))
i=1
while(i<=n):
    print('iPhone',i)
    i+=1
print('Oh,Thank you,')

Enter any number:5
iPhone 1
iPhone 2
iPhone 3
iPhone 4
iPhone 5
Oh,Thank you,


In [201]:
n=int(input("Enter any number:"))
avilable=5
i=1
while(i<=n):
    if i>avilable:
        print('Sorry! out of stack.')
        break;
    print('iPhone',i)
    i+=1
print('Oh,Thank you,')

Enter any number:10
iPhone 1
iPhone 2
iPhone 3
iPhone 4
iPhone 5
Sorry! out of stack.
Oh,Thank you,


# Fibonacci Sequence in Python

In [202]:
def fib(x):
    a=0
    b=1
    print(a)
    print(b)
    
    for i in range(2,x):
        c=a+b
        a=b
        b=c
        
        print(c)
        
num=int(input('Enter any number:'))
fib(num)

Enter any number:10
0
1
1
2
3
5
8
13
21
34


# Factorial Number using Python

In [203]:
num=int(input('Enter any number:'))
result=1
for i in range(1,num+1):
    result=result*i
print(result)

Enter any number:5
120


In [204]:
import math
num=int(input('Enter any number:'))
print(math.factorial(num))

Enter any number:5
120


# args in Python | Python Non-Keyword Arguments (args)

In [205]:
def my_mul(*num):
    r=1
    for i in num:
        r*=i
    print(r)
my_mul(2,5,6,9)

540


In [206]:
def my_mul(num1,*num):
    r=1
    for i in num:
        r*=i
    print(r)
my_mul(2,5,6,9)

270


In [207]:
def my_func(*argv):
    for i in argv:
        print(argv)
my_func('Hi','Welcome','to','study mart')

def my_func(arg1,*x):
    print("First argument : ",arg1);
    
    for i in x:
        print('Next arguments : ',x)

my_func('Hello','Welcome','to','study mart')

('Hi', 'Welcome', 'to', 'study mart')
('Hi', 'Welcome', 'to', 'study mart')
('Hi', 'Welcome', 'to', 'study mart')
('Hi', 'Welcome', 'to', 'study mart')
First argument :  Hello
Next arguments :  ('Welcome', 'to', 'study mart')
Next arguments :  ('Welcome', 'to', 'study mart')
Next arguments :  ('Welcome', 'to', 'study mart')


# kwargs in Python | Keyword Argument | *Args vs KwArgs

In [208]:
def myself(age,*others):
    print(age)
    print(others)
myself(22,'Hamid Hosen','East Delta university','Bangladesh')

22
('Hamid Hosen', 'East Delta university', 'Bangladesh')


In [209]:
def myself(age,*others):
    print(age)
    print(others)
myself(22,name='Hamid Hosen',versity='East Delta university',country='Bangladesh')

TypeError: myself() got an unexpected keyword argument 'name'

In [210]:
def myself(age,**others):
    print(age)
    print(others)
myself(22,name='Hamid Hosen',versity='East Delta university',country='Bangladesh')

22
{'name': 'Hamid Hosen', 'versity': 'East Delta university', 'country': 'Bangladesh'}


In [212]:
def myself(**others):
    #print(age)
    print(others)
myself(age=22,name='Hamid Hosen',versity='East Delta university',country='Bangladesh')

{'age': 22, 'name': 'Hamid Hosen', 'versity': 'East Delta university', 'country': 'Bangladesh'}


# What is Numpy? Python List vs Numpy Array

NumPy is one of the most powerful Python libraries. This article will outline the core features of the NumPy library. It will also provide an overview of the common mathematical functions in an easy-to-follow manner. More details are given below: 1. NumPy is an open-source numerical Python library. 2. NumPy contains a multi-dimensional array and matrix data structures. 3. It can be utilized to perform a number of mathematical operations on arrays such as trigonometric, statistical and algebraic routines. 4. NumPy is an extension of Numeric and Numarray. 5. The library contains a large number of mathematical, algebraic and transformation functions. 6. It also contains random number generators. 7. NumPy is a wrapper around a library implemented in C. 8. Pandas objects rely heavily on NumPy objects. Pandas extend Numpy.

In [213]:
list1=[1,3,5,7]
list2=[4,7,9,2]

print(list1*list2)

TypeError: can't multiply sequence by non-int of type 'list'

In [214]:
list1=[1,3,5,7]
list2=[4,7,9,2]

print(list1[1]*list2[2])

27


In [215]:
import numpy as np

list1=np.array([1,3,5,7])
list2=np.array([4,7,9,2])

print(list1*list2)

[ 4 21 45 14]


# Multidimensional Arrays in Python || 2D & 3D Arrays

In [216]:
import numpy as r
x=r.array([
    [1,2,3,4,5,6],
    [4,5,6,7,8,9]
])
print(x)

[[1 2 3 4 5 6]
 [4 5 6 7 8 9]]


In [217]:
from numpy import*

x=array([
    [1,2,3,4,5,6],
    [4,5,6,7,8,9]
])
print(x)

[[1 2 3 4 5 6]
 [4 5 6 7 8 9]]


In [218]:
print(x.dtype)

int32


In [219]:
print(x.ndim)

2


In [220]:
print(x.shape)

(2, 6)


In [221]:
print(x.size)

12


In [222]:
from numpy import*

x=array([
    [1,2,3,4,5,6],
    [4,5,6,7,8,9]
])
print(x)

y=x.flatten()
print(y)

[[1 2 3 4 5 6]
 [4 5 6 7 8 9]]
[1 2 3 4 5 6 4 5 6 7 8 9]


In [223]:
z=y.reshape(3,4)
print(z)

[[1 2 3 4]
 [5 6 4 5]
 [6 7 8 9]]


In [224]:
a=z.reshape(2,3,2)
print(a)

[[[1 2]
  [3 4]
  [5 6]]

 [[4 5]
  [6 7]
  [8 9]]]


In [225]:
print(a.ndim)

3


# Matrix in Python || Matrix Multiplication in Python 

In [226]:
import numpy as np

m1=[[1,2,3],
   [4,5,6],
   [7,8,9]
   ]

m2=([3,4,2],
    [7,8,9],
    [3,5,9]
   )
print(m1)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [227]:
import numpy as np

m1=([1,2,3],
   [4,5,6],
   [7,8,9]
   )

m2=([3,4,2],
    [7,8,9],
    [3,5,9]
   )
print(np.add(m1,m2))

[[ 4  6  5]
 [11 13 15]
 [10 13 18]]


In [228]:
print(np.subtract(m1,m2))

[[-2 -2  1]
 [-3 -3 -3]
 [ 4  3  0]]


In [229]:
print(np.dot(m1,m2))#roq*col

[[ 26  35  47]
 [ 65  86 107]
 [104 137 167]]


In [230]:
print(np.multiply(m1,m2))

[[ 3  8  6]
 [28 40 54]
 [21 40 81]]


# Zip Function in Python || Unzip || Zipping Two Lists

In [231]:
person_name=['hamid','hosen','azad','fahim']
person_age=[23,45,67,89]

print(person_name+person_age)

['hamid', 'hosen', 'azad', 'fahim', 23, 45, 67, 89]


In [233]:
print(list(zip(person_name,person_age)))

TypeError: 'list' object is not callable

[('hamid', 23), ('hosen', 45), ('azad', 67), ('fahim', 89)]

In [234]:
print(list(zip('1234',person_name,person_age)))

TypeError: 'list' object is not callable

[('1', 'hamid', 23), ('2', 'hosen', 45), ('3', 'azad', 67), ('4', 'fahim', 89)]

In [235]:
print(list(zip(person_name,person_age,'1234')))

TypeError: 'list' object is not callable

[('hamid', 23, '1'), ('hosen', 45, '2'), ('azad', 67, '3'), ('fahim', 89, '4')]

In [236]:
x=[('1', 'hamid', 23), ('2', 'hosen', 45), ('3', 'azad', 67), ('4', 'fahim', 89)]
print(list(zip(*x)))

TypeError: 'list' object is not callable

[('1', '2', '3', '4'), ('hamid', 'hosen', 'azad', 'fahim'), (23, 45, 67, 89)]

In [237]:
y=list(zip(*x))

print(y[0])
print(y[1])
print(y[2])

TypeError: 'list' object is not callable

('1', '2', '3', '4')
('hamid', 'hosen', 'azad', 'fahim')
(23, 45, 67, 89)

# Lambda Function in Python || Python Lambda (Anonymous Functions)

In [238]:
r=(lambda x,y,z: x*y*z)(2,5,9)
print(r)

90


# Map Function in Python || Map() in Python

In [239]:
def mul(n):
    return n*5;

result=[]
num=[3,5,7,9,2,1,5]

for i in num:
    result.append(mul(i))
print(result)

[15, 25, 35, 45, 10, 5, 25]


In [240]:
def mul(n):
    return n*5;

num=[3,5,7,9,2,1,5]
result=list(map(mul,num))
print(result)

TypeError: 'list' object is not callable

[15, 25, 35, 45, 10, 5, 25]

# Filter Function in Python || Python filter ( )

In [241]:
num1=[1,2,3,4,3,0,6,7,8,9,11,12,13,14]

result=list(filter((lambda n:n%2),num))
print("Odd Number: ",result)

TypeError: 'list' object is not callable

Odd Number:  [1, 3, 3, 7, 9, 11, 13]

In [242]:
num1=[1,2,3,4,3,0,6,7,8,9,11,12,13,14]

result=list(filter((lambda n:n%2==0),num))
print("Odd Number: ",result)

TypeError: 'list' object is not callable

Odd Number:  [2, 4, 0, 6, 8, 12, 14]

In [243]:
num1=[1,2,3,4,3,0,6,7,8,9,11,12,13,14]

result=list(filter((lambda n:n>5),num))
print("Odd Number: ",result)

TypeError: 'list' object is not callable

Odd Number:  [6, 7, 8, 9, 11, 12, 13, 14]

# Reduce Function in Python || Python reduce ( )

In [244]:
import functools

def two_num_sum(num1,num2):
    return num1+num2

list=[1,2,3,4,5]
print(functools.reduce(two_num_sum,list))

15


# Local Variable vs Global Variable in Python 

In [245]:
def fnc():
    rt=150
    print("Inside:",rt)
fnc()
print('Outside ',rt)


Inside: 150


NameError: name 'rt' is not defined

In [246]:
rt=100
def fnc():
    rt=150
    print("Inside:",rt)
fnc()
print('Outside ',rt)

Inside: 150
Outside  100


In [247]:
rt=100
def fnc():
    #rt=150
    print("Inside:",rt)
fnc()
print('Outside ',rt)

Inside: 100
Outside  100


In [248]:
rt=100
def fnc():
    global rt
    rt=rt+50
    print("Inside:",rt)
fnc()
print('Outside ',rt)

Inside: 150
Outside  150


# Default Arguments in Python || Python Default Arguments

In [249]:
def My_pow(a,b=5):
    return a**b#pow(a,b)

x=My_pow(2)
print(x)

32


In [250]:
def My_pow(a,b=5):
    return a**b#pow(a,b)

x=My_pow(2,3)
print(x)

8


In [251]:
def fnc(x='Hamid'):
    print('I am ',x)
fnc('(Hamid)')

I am  (Hamid)


# Recursion in Python | Recursion Explained 

In [252]:
import sys
print('List = ',sys.getrecursionlimit())
sys.setrecursionlimit(1500)

count=0
def my_fnc():
    global count
    count=count+1
    print('Study Mart ',count)
    my_fnc()
my_fnc()

List =  3000
Study Mart  1
Study Mart  2
Study Mart  3
Study Mart  4
Study Mart  5
Study Mart  6
Study Mart  7
Study Mart  8
Study Mart  9
Study Mart  10
Study Mart  11
Study Mart  12
Study Mart  13
Study Mart  14
Study Mart  15
Study Mart  16
Study Mart  17
Study Mart  18
Study Mart  19
Study Mart  20
Study Mart  21
Study Mart  22
Study Mart  23
Study Mart  24
Study Mart  25
Study Mart  26
Study Mart  27
Study Mart  28
Study Mart  29
Study Mart  30
Study Mart  31
Study Mart  32
Study Mart  33
Study Mart  34
Study Mart  35
Study Mart  36
Study Mart  37
Study Mart  38
Study Mart  39
Study Mart  40
Study Mart  41
Study Mart  42
Study Mart  43
Study Mart  44
Study Mart  45
Study Mart  46
Study Mart  47
Study Mart  48
Study Mart  49
Study Mart  50
Study Mart  51
Study Mart  52
Study Mart  53
Study Mart  54
Study Mart  55
Study Mart  56
Study Mart  57
Study Mart  58
Study Mart  59
Study Mart  60
Study Mart  61
Study Mart  62
Study Mart  63
Study Mart  64
Study Mart  65
Study Mart  66
Study 

RecursionError: maximum recursion depth exceeded while calling a Python object

# Factorial Using Recursion | Recursion Explained

In [253]:
def fnc(n):
    if n==0:
        return 1
    return n * fnc(n-1)

num=int(input("Enter any number:"))

result=fnc(num)
print("Result is = ",result)

Enter any number:5
Result is =  120


# Python Object-Oriented Programming | Programming Paradigms 

Programming Paradigms in Python. 1. Declarative Programming:- 1. Functional Programming 2. Logic Programming 2. Mathematical Programming 2. Imperative Programming: 1. Procedural Programming 2. Object-Oriented - Programming (OOP)

# Python Small Project | Text to Audio Converter | Text to Speech | Python Mini Project with Codes

gTTS (Google Text-to-Speech)is a Python library and CLI tool to interface with Google Translate text-to-speech API. We will import the gTTS library from the gtts module which can be used for speech translation. The text variable is a string used to store the user's input. os=The os module is a part of the standard library, or stdlib, within Python 3. This means that it comes with your Python installation, but you still must import it. All of the following code assumes you have os imported. Because it is not a built-in function, you must always import

In [255]:
import os

from gtts import gTTS

fh=open('audio.txt','r')
myText=fh.read().replace('\n'," ")
language='en'
output=gTTS(text=myText,lang=language,slow=False)
output.save('output.mp3')
fh.close()
os.system('start output.mp3')

0

# Python small project | Stopwatch with source code | Python mini project | Stopwatch using Python

tkinter=Out of all the GUI methods, tkinter is the most commonly used method. It is a standard Python interface to the Tk GUI toolkit shipped with Python. Python with tkinter is the fastest and easiest way to create the GUI applications. Creating a GUI using tkinter is an easy task. time=Python has a module named time to handle time-related tasks.

In [256]:
from tkinter import *
import time

def Main():
    global root

    root = Tk()
    root.title("Stopwatch made by @StudyMart")
    width = 500
    height = 200
    screen_width = root.winfo_screenwidth()
    screen_height = root.winfo_screenheight()
    x = (screen_width / 2) - (width / 2)
    y = (screen_height / 2) - (height / 2)
    root.geometry("%dx%d+%d+%d" % (width, height, x, y))
    Top = Frame(root, width=400)
    Top.pack(side=TOP)

    stopWatch = StopWatch(root)
    stopWatch.pack(side=TOP)
    Bottom = Frame(root, width=400)
    Bottom.pack(side=BOTTOM)
    Start = Button(Bottom, text='START', command=stopWatch.Start, width=10, height=3)
    Start.pack(side=LEFT)
    Stop = Button(Bottom, text='STOP', command=stopWatch.Stop, width=10, height=3)
    Stop.pack(side=LEFT)
    Reset = Button(Bottom, text='RESET', command=stopWatch.Reset, width=10, height=3)
    Reset.pack(side=LEFT)
    Exit = Button(Bottom, text='CLOSE', command=stopWatch.Exit, width=10, height=3)
    Exit.pack(side=LEFT)
    Title = Label(Top, text="StopWatch @studymart", font=("arial", 24), fg="white", bg="black")
    Title.pack(fill=X)
    root.config(bg="black")
    root.mainloop()


class StopWatch(Frame):

    def __init__(self, parent=None, **kw):
        Frame.__init__(self, parent, kw)
        self.startTime = 0.0
        self.nextTime = 0.0
        self.onRunning = 0
        self.timestr = StringVar()
        self.MakeWidget()

    def MakeWidget(self):
        timeText = Label(self, textvariable=self.timestr, font=("times new roman", 45), fg="white", bg="black")
        self.SetTime(self.nextTime)
        timeText.pack(fill=X, expand=NO, pady=5, padx=10)

    def Updater(self):
        self.nextTime = time.time() - self.startTime
        self.SetTime(self.nextTime)
        self.timer = self.after(50, self.Updater)

    def SetTime(self, nextElap):
        minutes = int(nextElap / 60)
        seconds = int(nextElap - minutes * 60.0)
        miliSeconds = int((nextElap - minutes * 60.0 - seconds) * 100)
        self.timestr.set('%02d:%02d:%02d' % (minutes, seconds, miliSeconds))

    def Start(self):
        if not self.onRunning:
            self.startTime = time.time() - self.nextTime
            self.Updater()
            self.onRunning = 1

    def Stop(self):
        if self.onRunning:
            self.after_cancel(self.timer)
            self.nextTime = time.time() - self.startTime
            self.SetTime(self.nextTime)
            self.onRunning = 0

    def Exit(self):
            root.destroy()
            exit()

    def Reset(self):
        self.startTime = time.time()
        self.nextTime = 0.0
        self.SetTime(self.nextTime)


if __name__ == '__main__':
    Main()

# Python small project | Text Editor using Python | Text Editor using Python with source code

In [257]:
from tkinter import *
from tkinter import filedialog

def new_file():
    text.delete(0.0,END)

def open_file():
    file1=filedialog.askopenfile(mode='r')
    data=file1.read()
    text.delete(0.0,END)
    text.insert(0.0,data) #Inserts data

def save_file():
    filename="Untitled.txt"
    data=text.get(0.0,END)
    file1=open(filename,"w")
    file1.write(data)

def save_as():
    file1=filedialog.asksaveasfile(mode='w')
    data=text.get(0.0,END)
    file1.write(data)

gui=Tk() #tkinter object.
gui.title("Text Creator")
gui.geometry("800x1000")
text=Text(gui)
text.pack() #Display the text
mymenu=Menu()
list1=Menu()
list1.add_command(label='Create File',command=new_file) #Create menus.
list1.add_command(label='Save File',command=save_file)
list1.add_command(label='Save File As',command=save_as)
list1.add_command(label='Open File',command=open_file)
list1.add_command(label='Exit',command=gui.quit)
mymenu.add_cascade(label='File hamid',menu=list1) #Create a file option.
gui.config(menu=mymenu)
gui.mainloop()

# Python Small Project | Tic Tac Toe Using Python | Python Tic Tac Toe Game With Source Codes

In [258]:
from tkinter import Tk,ttk,Button
from tkinter import messagebox
from random import randint

ActivePlayer = 1
p1 = []
p2 = []
mov = 0

def SetLayout(id,player_symbol):
    if id==1:
        b1.config(text= player_symbol)
        b1.state(['disabled'])
    elif id==2:
        b2.config(text= player_symbol)
        b2.state(['disabled'])
    elif id==3:
        b3.config(text= player_symbol)
        b3.state(['disabled'])
    elif id==4:
        b4.config(text= player_symbol)
        b4.state(['disabled'])
    elif id==5:
        b5.config(text= player_symbol)
        b5.state(['disabled'])
    elif id==6:
        b6.config(text= player_symbol)
        b6.state(['disabled'])
    elif id==7:
        b7.config(text= player_symbol)
        b7.state(['disabled'])
    elif id==8:
        b8.config(text= player_symbol)
        b8.state(['disabled'])
    elif id==9:
        b9.config(text= player_symbol)
        b9.state(['disabled'])

def CheckWinner():
    global mov
    winner = -1

    if(1 in p1) and (2 in p1) and (3 in p1):
        winner = 1
    if(1 in p2) and (2 in p2) and (3 in p2):
        winner = 2

    if(4 in p1) and (5 in p1) and (6 in p1):
        winner = 1
    if(4 in p2) and (5 in p2) and (6 in p2):
        winner = 2

    if(7 in p1) and (8 in p1) and (9 in p1):
        winner = 1
    if(7 in p2) and (8 in p2) and (9 in p2):
        winner = 2

    if(1 in p1) and (4 in p1) and (7 in p1):
        winner = 1
    if(1 in p2) and (4 in p2) and (7 in p2):
        winner = 2

    if(2 in p1) and (5 in p1) and (8 in p1):
        winner = 1
    if(2 in p2) and (5 in p2) and (8 in p2):
        winner = 2

    if(3 in p1) and (6 in p1) and ( 9 in p1):
        winner = 1
    if(3 in p2) and (6 in p2) and (9 in p2):
        winner = 2

    if(1 in p1) and (5 in p1) and ( 9 in p1):
        winner = 1
    if(1 in p2) and (5 in p2) and (9 in p2):
        winner = 2

    if(3 in p1) and (5 in p1) and ( 7 in p1):
        winner = 1
    if(3 in p2) and (5 in p2) and (7 in p2):
        winner = 2

    if winner ==1:
        messagebox.showinfo(title="Congratulations!",
            message="First Player is the winner")
    elif winner ==2:
        messagebox.showinfo(title="Congratulations!",
            message="Second Player is the winner")
    elif mov ==9:
        messagebox.showinfo(title="Draw",
            message="Opps! It's a Draw Match!")

def ButtonClick(id):
    global ActivePlayer
    global p1,p2
    global mov

    if(ActivePlayer ==1):
        SetLayout(id,"X")
        p1.append(id)
        mov +=1
        root.title("Tic Tac Toe : Player Two")
        ActivePlayer =2

    elif(ActivePlayer==2):
        SetLayout(id,"O")
        p2.append(id)
        mov +=1
        root.title("Tic Tac Toe : Player One")
        ActivePlayer =1
    CheckWinner()
def AutoPlay():
    global p1; global p2
    Empty = []
    for cell in range(9):
        if(not((cell +1 in p1) or (cell +1 in p2))):
            Empty.append(cell+1)
    try:
        RandIndex = randint(0,len(Empty) -1)
        ButtonClick(Empty[RandIndex])
    except:
        pass
def EnableAll():
    b1.config(text= " ")
    b1.state(['!disabled'])
    b2.config(text= " ")
    b2.state(['!disabled'])
    b3.config(text= " ")
    b3.state(['!disabled'])
    b4.config(text= " ")
    b4.state(['!disabled'])
    b5.config(text= " ")
    b5.state(['!disabled'])
    b6.config(text= " ")
    b6.state(['!disabled'])
    b7.config(text= " ")
    b7.state(['!disabled'])
    b8.config(text= " ")
    b8.state(['!disabled'])
    b9.config(text= " ")
    b9.state(['!disabled'])


def Restart():
    global p1,p2,mov,ActivePlayer
    p1.clear(); p2.clear()
    mov,ActivePlayer = 0,1
    root.title("Tic Tac Toe : Player One")
    EnableAll()


root = Tk()
root.title("Tic Tac toe : Player One")
st = ttk.Style()
st.configure("my.TButton", font=('Chiller',24,'bold'))

b1 = ttk.Button(root, text=" ", style="my.TButton")
b1.grid(row=1, column=0, sticky="snew", ipadx=75,ipady=50)
b1.config(command = lambda : ButtonClick(1))


b2 = ttk.Button(root, text=" ",style ="my.TButton")
b2.grid(row=1, column=1, sticky="snew", ipadx=50, ipady=50)
b2.config(command = lambda : ButtonClick(2))

b3= ttk.Button(root, text=" ",style="my.TButton")
b3.grid(row=1, column=2, sticky="snew", ipadx=50,
        ipady=50)
b3.config(command = lambda : ButtonClick(3))

b4 = ttk.Button(root, text=" ",style="my.TButton")
b4.grid(row=2, column=0, sticky="snew", ipadx=50,
        ipady=50)
b4.config(command = lambda : ButtonClick(4))

b5 = ttk.Button(root, text=" ",style="my.TButton")
b5.grid(row=2, column=1, sticky="snew", ipadx=50,
        ipady=50)
b5.config(command = lambda : ButtonClick(5))

b6 = ttk.Button(root, text=" ",style="my.TButton")
b6.grid(row=2, column=2, sticky="snew", ipadx=50,
        ipady=50)
b6.config(command = lambda : ButtonClick(6))

b7 = ttk.Button(root, text=" ",style="my.TButton")
b7.grid(row=3, column=0, sticky="snew", ipadx=50,
        ipady=50)
b7.config(command = lambda : ButtonClick(7))

b8 = ttk.Button(root, text=" ",style="my.TButton")
b8.grid(row=3, column=1, sticky="snew", ipadx=50,
        ipady=50)
b8.config(command = lambda : ButtonClick(8))

b9 = ttk.Button(root, text=" ",style="my.TButton")
b9.grid(row=3, column=2, sticky="snew", ipadx=50,
        ipady=50)
b9.config(command = lambda : ButtonClick(9))

Button(text="Tic Tac Toe ", font=('times new roman', 18, 'bold'), bg='black', fg='white',
            border=5, width=8,command = lambda :Restart()).grid(row=0, column=1, sticky="we")
root.resizable(0,0)
root.mainloop()