In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
df=pd.read_csv("1-TF-IDF Vectorizer  Feature Extraction Techniques DataSet/emails.csv")
df

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5728 rows x 2 columns]

In [3]:
df['spam'].value_counts()

0    4360
1    1368
Name: spam, dtype: int64

In [4]:
df.drop_duplicates(inplace=True)

In [5]:
df['spam'].value_counts()

0    4327
1    1368
Name: spam, dtype: int64

In [6]:
df

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5695 rows x 2 columns]

In [7]:
df.isnull().sum()

text    0
spam    0
dtype: int64

### separate x and y

In [8]:
x=df.text.values

In [9]:
y=df.spam.values

### Split Dataset

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x_train,x_test,y_trian,y_test=train_test_split(x,y,test_size=0.2)

### Data Preprocessing

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [13]:
#object create
cv=TfidfVectorizer()

In [14]:
res=cv.fit_transform(x_train)

In [15]:
res.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

### ML Algorithm

In [16]:
from sklearn.naive_bayes import MultinomialNB

In [17]:
model=MultinomialNB()

In [18]:
model.fit(res,y_trian)

MultinomialNB()

In [19]:
xtest=cv.transform(x_test)

In [20]:
xtest.toarray()

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.03789637, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.08069325, 0.05371828, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [21]:
model.score(xtest,y_test)

0.8770851624231782

In [22]:
emails = ['hey i am lokking for machine learning tutorial in begali language','hey you win an iphone x giveaway for free please do the survey']

In [23]:
cv_emails=cv.transform(emails)

In [24]:
model.predict(cv_emails)

array([0, 0], dtype=int64)

### Performance

In [25]:
pred=model.predict(xtest)

In [26]:
pred

array([1, 0, 0, ..., 1, 0, 0], dtype=int64)

In [27]:
from sklearn.metrics import accuracy_score

In [28]:
accuracy_score(y_test,pred)

0.8770851624231782

### Confusion matrix

In [29]:
from sklearn.metrics import confusion_matrix

In [30]:
confusion_matrix(y_test,pred)

array([[875,   0],
       [140, 124]], dtype=int64)

### TP=859,FP=0,FN=157,TN=123
### CLASSIFICATION

In [31]:
from sklearn.metrics import classification_report

In [32]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.86      1.00      0.93       875
           1       1.00      0.47      0.64       264

    accuracy                           0.88      1139
   macro avg       0.93      0.73      0.78      1139
weighted avg       0.89      0.88      0.86      1139

